import { GiftItem } from '@/types';

export const mockGifts: GiftItem[] = [
  {
    id: '1',
    tenant_id: 'tenant-1',
    name: 'Jogo de Jantar 30 Peças',
    description: 'Um lindo jogo de jantar em cerâmica para recebermos nossos convidados com muito amor.',
    price: 850.00,
    room: 'cozinha',
    color: 'Branco/Off-white',
    store_name: 'Camicado',
    store_link: 'https://camicado.com.br',
    status: 'disponivel',
    is_featured: false,
    image_url: 'https://picsum.photos/seed/dinnerware/800/800',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    tenant_id: 'tenant-1',
    name: 'Air Fryer 4L',
    description: 'Para facilitar nossa rotina e prepararmos refeições mais saudáveis.',
    price: 450.00,
    room: 'cozinha',
    color: 'Preto',
    store_name: 'Amazon',
    store_link: 'https://amazon.com.br',
    status: 'disponivel',
    is_featured: false,
    image_url: 'https://picsum.photos/seed/airfryer/800/800',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    tenant_id: 'tenant-1',
    name: 'Conjunto de Toalhas Fio Penteado',
    description: 'Toalhas macias e confortáveis para o nosso dia a dia.',
    price: 220.00,
    room: 'banheiro',
    color: 'Branco',
    store_name: 'Zelo',
    store_link: 'https://zelo.com.br',
    status: 'reservado',
    is_featured: false,
    image_url: 'https://picsum.photos/seed/towels/800/800',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    tenant_id: 'tenant-1',
    name: 'Aspirador Vertical Sem Fio',
    description: 'Praticidade para manter nossa casa sempre limpa.',
    price: 1200.00,
    room: 'lavanderia',
    color: 'Cinza',
    store_name: 'Fast Shop',
    store_link: 'https://fastshop.com.br',
    status: 'disponivel',
    is_featured: false,
    image_url: 'https://picsum.photos/seed/vacuum/800/800',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    tenant_id: 'tenant-1',
    name: 'Jogo de Cama Fios Egípcios',
    description: 'Conforto para o nosso novo quarto.',
    price: 320.00,
    room: 'quarto',
    color: 'Branco',
    store_name: 'Casas Bahia',
    store_link: 'https://casasbahia.com.br',
    status: 'comprado',
    is_featured: false,
    image_url: 'https://picsum.photos/seed/bed/800/800',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    tenant_id: 'tenant-1',
    name: 'Cafeteira Expresso',
    description: 'Para nossos cafés da manhã especiais.',
    price: 650.00,
    room: 'cozinha',
    color: 'Vermelha',
    store_name: 'Amazon',
    store_link: 'https://amazon.com.br',
    status: 'disponivel',
    is_featured: false,
    image_url: 'https://picsum.photos/seed/coffee/800/800',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    tenant_id: 'tenant-1',
    name: 'Tapete para Sala 2x3m',
    description: 'Para deixar nossa sala mais aconchegante.',
    price: 890.00,
    room: 'sala',
    color: 'Bege',
    store_name: 'Tok&Stok',
    store_link: 'https://tokstok.com.br',
    status: 'disponivel',
    is_featured: false,
    image_url: 'https://picsum.photos/seed/rug/800/800',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '8',
    tenant_id: 'tenant-1',
    name: 'Conjunto de Taças de Cristal',
    description: 'Para brindarmos os momentos felizes.',
    price: 350.00,
    room: 'sala',
    color: 'Transparente',
    store_name: 'Camicado',
    store_link: 'https://camicado.com.br',
    status: 'disponivel',
    is_featured: false,
    image_url: 'https://picsum.photos/seed/glasses/800/800',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];
